FROM php:8.1-fpm-alpine
#RUN echo "@testing https://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
#    && apk update \
#    && apk upgrade \
#    && apk --update add --no-cache php8-pgsql@testing php8-pdo_pgsql@testing
#RUN docker-php-ext-enable pdo_pgsql;

RUN echo "@testing https://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk update && apk --no-cache add postgresql-dev php8-pgsql@testing

RUN docker-php-ext-install pdo_pgsql
RUN docker-php-ext-enable pdo_pgsql

WORKDIR /var/www